### ISSUE TITLE
Ten-year reproducibility challenge: friction coefficients of mixed globular/chain molecules (1995)

### ISSUE THREAD

**Issue by charlestonchas** [ReScience/submissions#26]
**Original article:**
Charles H. Robert. "Estimating friction coefficients of mixed globular/chain molecules, such as protein/DNA complexes." Biophys. J. 69 (Sept. 1995), pp. 840–848
[https://doi.org/10.1016/S0006-3495(95)79957-X](https://doi.org/10.1016/S0006-3495(95)79957-X)

**PDF URL:**
revised MS
[https://github.com/charlestonchas/rehydro-rescience-submit/blob/master/tex/article.pdf](https://github.com/charlestonchas/rehydro-rescience-submit/blob/master/tex/article.pdf)

**Metadata URL:**  
[https://github.com/charlestonchas/rehydro-rescience-submit/blob/master/tex/metadata.yaml](https://github.com/charlestonchas/rehydro-rescience-submit/blob/master/tex/metadata.yaml)

**Code URL:**  
[https://zenodo.org/record/3878075](version 1.0.2 https://zenodo.org/record/3878075)

**Scientific domain:**
Structural Biology, Hydrodynamics

**Programming language:** 
Mathematica

**Suggested editor:**  
Konrad Hinsen

**Comment by khinsen** [comment]
Thanks for your submission! I will start looking for a reviewer.

**Comment by khinsen** [comment]
@ChrisRackauckas Can you review this submission? I know it's not fully in your field of expertise, but it isn't terribly remote either. And I can help out with the biophysics aspects myself. What I am mainly looking for is Mathematica expertise.

**Comment by mstimberg** [comment]
> What I am mainly looking for is Matlab expertise.

Probably just a typo, but note that the paper is using *Mathematica*, not Matlab.

**Comment by khinsen** [comment]
@mstimberg Thanks for pointing this out, it was indeed a typo!

**Comment by ChrisRackauckas** [comment]
Sorry, I will not have adequate time to properly review this.

**Comment by khinsen** [comment]
@ChrisRackauckas OK, thanks for the quick feedback!

**Comment by charlestonchas** [comment]
I updated the initial submission post to link to the zenodo code entry (rehydro) containing additional pdf versions of the Mathematica notebooks that were omitted in the original version.

Here it is as well: [https://doi.org/10.5281/zenodo.3747007](url)

**Comment by khinsen** [comment]
Activity note: I am contacting potential reviewers outside of the GitHub universe. Silence should not be interpreted as absence of progress!

**Comment by khinsen** [comment]
*[Gerald Kneller](http://dirac.cnrs-orleans.fr/~kneller/) kindly accepted to review this article. Since he doesn't have a GitHub account, I transmit his review received by mail:*

Report on manuscript 

[Rp] Reproducibility report: Estimating friction coefficients of mixed
globular/chain molecules, such as protein/DNA complexes. [Biophys J
69, 840-848 (1995)]

By Charles ROBERT

The paper describes a reproducibility study concerning an article
published in 1995 [Biophys J, 69, 840-848 (1995)], dealing with the
estimation of friction coefficients of mixtures of macromolecules with
open chain and globular form, respectively. The calculations for this
article have been performed with Wolfram's Mathematica Package for
symbolic and numerical calculations and the targets for the
reproducibility study are four Mathematica Notebooks, named
Figure2.nb - Figure5.nb, which produce essentially figures and tables.
The original notebooks from 1995 cannot be used any more, because of
the transition from 32 bit to 64 bit technology, and test notebooks are 
provided for Mathematica 5.2 (2005) and 12.0 (2019).

I performed the test runs with Mathematica 12.0 for both series of
targets which ran properly after a modification of the code to read in
the s6.1_repro.m and extra.m libraries. From all I could see, the
figures and tables were reproduced, where the figures were checked by
visual inspection and the tables were spot-checked.

**Comment by khinsen** [comment]
@charlestonchas Would it be possible to include the reproduced figures and tables in the text of your submission? That would permit every reader to judge similarity with the originals, not only those who have access to Mathematics.

**Comment by charlestonchas** [comment]
Thanks to Gerald Kneller and yourself for taking the time to review the manuscript and provide feedback. I'll modify the MS to add the tables and figures generated by Mathematica as soon as possible; it will indeed be better to include them in the article itself.

**Comment by charlestonchas** [comment]
@khinsen I added the requested figures to the MS, along with a corresponding table, and took the opportunity to improve the clarity of the presentation (an advantage of leaving the MS alone for a few weeks). I also added the tex to the github repository to facilitate diffs. The pdf, metadata, and code links at the top of this issue have been updated accordingly.

The original article figures were created with the aid of additional software that is no longer available, so I added new Mathematica 12 code to take the reproduced values (the calculations themselves were untouched) and produce figures that closely match the original formatting. These files were updated in the software distribution in the Zenodo repository (rehydro version 1.0.2).

Please let me know any additional steps needing to be made.

**Comment by khinsen** [comment]
@charlestonchas Thanks for the update! I'd say this looks good and... I proclaim this submission accepted!

I will start the publication process, which may or may not involve further requests to you, depending on how it goes.

**Comment by khinsen** [comment]
@charlestonchas Could you please review the metadata updates at https://github.com/ReScience/submissions/issues/26? I can then generate the final PDF myself because you have used our template.

**Comment by charlestonchas** [comment]
That's good news! I updated the metadata.yaml (using one of your articles as a reference!), but there are a few things missing, notably in the "contributors" section. Please check my work!

**Comment by khinsen** [comment]
@charlestonchas Looks good overall, but requires two more corrections:
1. DOIs in our metadata are DOIs, not URLs pointing to a DOI resolver.
2. Under "contributors", the "editor" entry is required for publication.

**Comment by charlestonchas** [comment]
Sorry; done!

**Comment by khinsen** [comment]
The article has been published (http://doi.org/10.5281/zenodo.3886412) and will soon be listed on the ReScience Web site!

**Comment by khinsen** [comment]
@charlestonchas The final metadata and PDF are at https://github.com/charlestonchas/rehydro-rescience-submit/pull/1 - just accept the pull request and your repository is up to date!

**Comment by charlestonchas** [comment]
Great! Pull request acccepted

_____________________

**Comment by rougier** [comment]
It's online
