### ISSUE TITLE
[Re] Assortative matching and search

### ISSUE THREAD

**Issue by fgeoffroy** [ReScience/submissions#47]
Dear Editors,

I would like to request a review for the following replication.

**Original articles:**
- Shimer, R., and Smith, L. (2000). Assortative matching and search. Econometrica, 68(2), 343–369. http://doi.org/10.1111/1468-0262.00112
- Smith, L. (2006). The Marriage Model with Search Frictions. J. Political Econ., 114(6), 1124–1144. https://doi.org/10.1086/510440

**PDF URL:** https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/blob/main/article/article.pdf
**Metadata URL:** https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/blob/main/article/metadata.yaml
**Code URL:** https://github.com/fgeoffroy/-Re-Assortative-matching-and-search

**Scientific domain:** Game theory
**Programming language:** Python
**Suggested editor:**

**Comment by rougier** [comment]
Thank you for your submission and sorry for the delay. We'll assign an editor soon.

**Comment by rougier** [comment]
Actually, I can edit it.

**Comment by rougier** [comment]
@eddelbuettel @AurelienNioche Could you review this short submission in econometrics?

**Comment by eddelbuettel** [comment]
I could take a look but the self-selected field is game theory which is less my beef.

**Comment by AurelienNioche** [comment]
I agree that the label 'game theory' would be a better match than CS. I am also not familiar with Becker's model, but I can check that the code is doing what is supposed to do, and that I can reproduce the results.

**Comment by rougier** [comment]
Sorry for the mislabeling (I need to add more). For the revie,w you don't need to be specialist of the domain, only to appreciate if the results have been replicated as intended. If you can test the code, that's even better.

No firm deadline for review, I will remind you in one month.

**Comment by eddelbuettel** [comment]
### Reproduction of _Assortative matching and search_  for Shimer and Smith (2000) and Smith (2006) 

The submission reproduces results from two seminal paper in game theory and matching.  We find the reproduction to be faithful, replicable, and carefully executed.  Minor comments follow.

#### Paper

The [submitted paper](https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/blob/main/article/article.pdf) is clearly written and introduces the scientific content, problem setting, and relevant references in five pages.  It discusses the results carefullu, in particular the ability to reproduce all but one figure.  The lack of reproducibility of the final is reasoned about in some detail revealing contact with the original author, lack of source code for that part of the original study as well some conjecture about possibly parameter misprints and possible approximation.  Four pages present the reproduced figures which are also presented in the corresponding [reproduction code repository](https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/tree/main/figures).

#### Code

Usage and requirement of the [submitted code](https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/tree/main/code) are detailed appropriately.  We appreciate that the required software packages are both small in numbers (only a Python interpreter plus two packages) and very mainstream (NumPy, Matplotlib). Yet we find the description overly stringent; Python code can be executed in environments other than Conda.  The author lists Ubuntu 18.04 as the platform for his work; we suspect the code would have worked with the default setup. We reproduced everything under the (current) Ubuntu 20.10 release with versions 3.8.6 of Python, 1.18.4 of NumPy and 3.3.0 of Matplotlib. This would suggest that a less restrictive description might be suitable.  If the author were truly concerned about versions, maybe a small Docker container with these versions could be provided too.

The code itself is commented and clearly enough written.  My default editor and it [elpy](https://github.com/jorgenschaefer/elpy) follow some coding guidelines and bemoan a lack of some `def` statements in `main.py` as well as an inappropriate number of lines---but I tend to find those nags to be overly stringent so this is not a real concern.

#### Figures

The main outcome of the reproduction are 20 pdf files.  All appear to be identical to the [submitted versions](https://github.com/fgeoffroy/-Re-Assortative-matching-and-search/tree/main/figures).  As "eye-balling" figure has its limits, we made use of two R packages to i) convert the pdf files to png graphics and to ii) run a "visual test" comparing original and reproduction.  Doing so is difficult, and has limits but we found the package used ([visualTest](https://github.com/MangoTheCat/visualTest), on GitHub but sadly not published to CRAN) appropriate (and we also use it in teaching and marking).  The comparison script, in essence a loop over all all files with temporary file creation, conversion and comparison for each file, is below.

#### Disclaimer

This is my first review for ReScience, so please do lot me know if anything is insufficient or unclear.  Game theory is also not something I have really touched since the graduate school days (quite some time ago) but as there are few other economists among the ReScience reviewer, I hope that this will still be of help.   

#### Appendix 

The ad-hoc R script follows.  The two top-level directory assignment may need local adjustments.

```r

## Compare two sets of pdf files for https://github.com/ReScience/submissions/issues/47
## Dirk Eddelbuettel, Feb 2021, released under GPL 2 or later

library(pdftools)		# on CRAN: to convert pdf to png
library(visualTest)		# at github.com/MangoTheCat/visualTest: to assess figure similarity

dirA <- "code/figures"          # soft link into author repo
dirB <- "re-run-figures"        # output of reproduction

pdffiles <- list.files(dirA, pattern="*.pdf")

for (f in pdffiles) {
    ## construct filenames in original and reproduced directories
    fileA <- file.path(dirA, f)
    fileB <- file.path(dirB, f)
    stopifnot(`no reproduced file found` = file.exists(fileB))

    ## create two tempfiles and produces png variants
    tfA <- tempfile(fileext=".png")
    tfB <- tempfile(fileext=".png")
    pdf_convert(fileA, format="png", filenames=tfA, verbose=FALSE)
    pdf_convert(fileB, format="png", filenames=tfB, verbose=FALSE)

    ## compare these png variants for exactness (approximately but still...)
    stopifnot(`disparity found` = isSimilar(tfA, tfB, exact=TRUE))

    ## report progress
    cat("Processed and compared", f, "without issues.\n")
}

cat("Done. No issues.\n")
```

**Comment by rougier** [comment]
@eddelbuettel Many thanks for the (fast) review that is exactly what is expected.

@fgeoffroy Could you address @eddelbuettel comments. I think the inclusion of the R script that @eddelbuettel indly offered would be a nice addition to your work. As for the less restrictive environment, I think it makes sense to loosen it a bit since your work is generic enough.

**Comment by fgeoffroy** [comment]
Dear all,

Thank you @eddelbuettel for your review and @rougier for your suggestions. I have updated the code, article and README file accordingly in the repository.

To answer @eddelbuettel's comments:

- I agree that the versioning description was too stringent, given that the packages used are very common. I have modified the README file so that the versioning aspect is no longer presented as a major issue. I have kept the Conda environment only for tractability reasons.

- In the `main.py` file, I assume that the lack of `def` statements that you mentioned corresponds to the use of `lambda` functions. Accordingly, I have replaced them for `def` statements in all python files.

- I have not changed the length of the `main.py` file, because I also do not think it is a real concern and, here, it is mostly designed to give information about each figure.

- I have also made minor aesthetic changes so that the python files follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/) guidelines.

- I find the visual comparison idea very relevant, so I have included the R script provided by @eddelbuettel, as suggested by @rougier. Do you agree with this decision @eddelbuettel? It is mentioned that you are the author of this script in the README file, the article and in the script itself. To facilitate the comparison process, I have changed the folder structure: the article figures are now located in `article/figures/` and the output of the main python script goes to `code/figures/`. The R script is named `compare_images.R` and is located in the `code/` subfolder.

Lastly, thanks to @AurelienNioche's reply, I have realized that I had not mentioned the link between the replicated work and Becker's famous model. Thus, I have added a sentence and three relevant references in the Introduction.

**Comment by eddelbuettel** [comment]
That sounds good to me on all counts.

**Comment by rougier** [comment]
@AurelienNioche No pressure but if you send your review by the end of next week, I think we can hit a record as the fastest time for review  :)

**Comment by AurelienNioche** [comment]
We'll try my best for this record to happen!;)

**Comment by AurelienNioche** [comment]
@fgeoffroy 
Dear Author,

I found the paper well written, clearly explaining what could be reproduced, what could not (at least not without modifying the parameterization), and how to reproduce the results from Shimer and Smith (2020), and Smith (2006). 

Here are a few minor comments, for both the paper and the code:
  
## Paper

### Results

Figure 3: It may be useful to have a 2 x 2 figure, with an additional panel showing that using delta = 1.1 leads to failure to replicate Figure 2 from [11].

### Not cristal clear
* line 23: it will probably make sense to introduce the articles chronologically   
* line 23: "on both types" => this is confusing, as both NTU and TU depend on types of both agents, but not in the same way (3rd line of the equation following line 62 and 3rd line of the equation line 67). Is there a way to make that more clear?
* line 25: this case is called 'Transferable Utility', right?
* line 95: it should be "has been modified by more than epsilon", or similar
* line 127-128: "the higher oneʼs type, the higher the minimum type that one is willing to accept as a partner" => could probably be expressed in a clearer way
* line 129: "Here, there is no Positive Assortative Matching at the equilibrium" => by 'here', you mean "contrarily to the results presented in Fig. 1", right?
* line 160: could you describe here if the results match your expectations? it seems to be, but it would be better to have it said.

### Typos 
* line 15: "itterature" instead of "litterature"
* line 47: "in" instead of "is "
* figure 3 caption: For B, delta = 1.1
* several places: "figure X" indead of "Figure X" (capitalization)

## Code 

### Execution
 
Everything worked out of the box for me. 

### Redaction

I appreciate the inline comments and spaced code, as well as the very clear and detailed README.

A few minor comments:
* camel case and snake case are both used indifferently for naming variables, while according to the PEP-8 convention, snake case should be preferred
* run_TU.py:
	* line 28: variable "values" is not used
	* line 50: useless parenthesis
	* line 47/48: parameters should be arguments of the function 
* run_NTU.py:
	* same as run_TU.py

**Comment by rougier** [comment]
@AurelienNioche Fantastic, thanks.
@fgeoffroy Can you address the minor comments by @AurelienNioche After that, I think we can proceed with publication.

**Comment by fgeoffroy** [comment]
Dear @AurelienNioche,

Thank you very much for your review and suggestions.

To answer your comments on the article:

- For Figure 3, I have added the sub-figure which shows a failure to replicate Figure 2 from [11] with delta = 1.1.

- In the third paragraph of the Introduction, I have modified the description of TU and NTU to make the distinction clearer.

- In the last step of the algorithm, the matching set `A` is a matrix of zeros and ones. The stopping criteria of the algorithm is thus simply when the matrix is identical to its value in the previous step.

- In the "Shimer & Smith 2000" section, I have modified the description of PAM to improve clarity as you suggested.

- In the "Gaussian distribution" section, I have added a description of the results, especially on the effect of the standard deviation.

To answer your comments on the code:

- I have modified the code to use the snake case naming convention.

- The useless variable and parenthesis have been removed.

- The parameter `tol` (the absolute tolerance level for the fixed-point iteration) is now an argument of the `find_equilibrium_TU` and `find_equilibrium_NTU` functions. The variable `e` is the error which is minimized by the fixed-point iteration. Its initial value was previously 1. For clarity, I have changed it to `sys.float_info.max`, the maximal float value in Python.

Thank you again @eddelbuettel and @AurelienNioche for you comments, I think they really improved the readability and quality of this replication. Thank you @rougier for the very fast and efficient review!

**Comment by rougier** [comment]
@AurelienNioche If you're satisfied with @fgeoffroy, I think we can accept the submission! Congratulations @fgeoffroy ! 
I'll need the URL to your article repository for the publication. In the meantime, can you save your code at https://www.softwareheritage.org/save-and-reference-research-software/ (the process is straightforwared and you should obtain a swid that is needed for publication).

**Comment by fgeoffroy** [comment]
@rougier I have saved the code at the following SWHID: swh:1:dir:c4b7d774ab458f90c433e321ab969d3f12e410de
I have also reserved a DOI (10.5281/zenodo.4607228), but I just miss some information before I publish it:
- the article number (asked in the `metadata.yaml` file)
- the journal volume
- the journal issue

Or should I proceed with the publication on Zenodo and you give me these information afterwards? I'm not sure about the procedure.

**Comment by rougier** [comment]
Oh, I will handle publication in fact. I just needed the SWHID. And sorry for the delay.

**Comment by rougier** [comment]
Here is the sandbox version: https://sandbox.zenodo.org/record/753083. Can you check if this looks good? If so, I'll publish the final article.

**Comment by fgeoffroy** [comment]
Thank you very much for handling this!
The long SWHID is somehow messing with the format, but it's not problematic and everything else seems perfect.

**Comment by rougier** [comment]
I noticed that too yes. I think we may need to change the template a bit. If you want to fix your article, I can make a PR on your repo and you can try to fix it. Then I'll publish it.

**Comment by fgeoffroy** [comment]
I updated the article on the github repo with a fix for the SWHID, the article number, journal volume and issue and the sandbox DOI that you created. Is that enough? If it is to much trouble, then you can just publish the previous version, the formatting problem is really minor.

**Comment by rougier** [comment]
Sorry for the delay. Can you tell what did you change in the template such I can do the same on my side.  The final (real) DOI will be different such that I need to be able to compile your article.

**Comment by fgeoffroy** [comment]
Yes sorry, I simply added a linebreak before the SWH in the header.tex file:
`\ifdefempty{\codeSWH}{.}{ -- \\ SWH \href{https://archive.softwareheritage.org/\codeSWH/}{\detokenize\expandafter{\codeSWH}}.}`

**Comment by rougier** [comment]
Thanks. It's online: https://rescience.github.io/bibliography/Geoffroy_2021.html
