### ISSUE TITLE
ICLR Reproducibility Challenge Editorial

### ISSUE THREAD

**Issue by koustuvsinha** [ReScience/submissions#5]
**Title:** ICLR Reproducibility Challenge 2019
**PDF URL:** https://github.com/koustuvsinha/iclr19_rc_editorial/blob/master/article.pdf
**Metadata URL:** https://github.com/koustuvsinha/iclr19_rc_editorial/blob/master/metadata.yaml
**Suggested editor:** Nicolas Rougier, Konrad Hinsen

**Comment by rougier** [comment]
Larochell -> Larochelle ?

**Comment by koustuvsinha** [comment]
@rougier thanks! fixed them now

**Comment by khinsen** [comment]
I am a bit late in looking at this because I was drowning in other stuff recently, sorry. I did have a look at the editorial and the submissions today. Everything looks very good: the editorial does a good job of describing the context and highlighting the strengths of each article, and the individual articles are well written. My knowledge of the domain is insufficient to say more about them, so I'll stop here and just say that I am happy to see these nice contributions to ReScience!

**Comment by rougier** [comment]
@koustuvsinha I'm editing your editorial. Do you confirm that none of the authors has an ORCID ?

**Comment by reproducibility-org** [comment]
Hi @rougier, sorry my ORCID id is 0000-0002-2803-9236. I don't have the information about my co-authors, unfortunately!

**Comment by koustuvsinha** [comment]
Hi @rougier, sorry my ORCID id is 0000-0002-2803-9236. I don't have the information about my co-authors, unfortunately!

**Comment by rougier** [comment]
Can you check everything is ok: https://www.dropbox.com/s/qu5u4fmmrbp3ux1/editorial.pdf?dl=0

**Comment by rougier** [comment]
You can access it at: https://github.com/rougier/ICLR-2019/tree/master/editorial

**Comment by koustuvsinha** [comment]
Looks good to me!
