### ISSUE TITLE
[Re] Modeling habits as self-sustained patterns of sensorimotor behavior

### ISSUE THREAD

**Issue by snowgoon88** [ReScience/submissions#51]
**Original article:** Egbert M. D., Barandiaran X. E. (2014) Modeling habits as self-sustaining patterns of sensorimotor behavior. Frontiers in Human Neuroscience, 8(590).

**PDF URL:** https://members.loria.fr/ADutech/Papier/rescience_egbert14_by_GillardFixDutech.pdf
**Metadata URL:**  
**Code URL:**  https://gitlab.inria.fr/openbiscuit/rescience_egbert14
(code is in directory 'python', latex for paper in 'article_rescience-template')

**Scientific domain:**  Computational Neuroscience
**Programming language:**  python
**Suggested editor:**  ? (maybe not Nicolas ROUGIER (too close))

**Comment by rougier** [comment]
Thanks for the submission and sorry for the delay. We'll assign an editor soon.

**Comment by rougier** [comment]
@gdetor @oliviaguest @otizonaizit @eroesch @benoit-girard  Can one of you edit this submission in Neuroscience / Python (I can't, I'm too close to the authors)

**Comment by benoit-girard** [comment]
Well, given the topic, I could act as a reviewer, instead...

**Comment by gdetor** [comment]
I can edit the submission

**Comment by gdetor** [comment]
@anne-urai Could you review this submission?
I assume @benoit-girard you could review as well.

**Comment by anne-urai** [comment]
Happy to review. However, the next months I have quite a high teaching load so this may take some time, would that be OK?

**Comment by benoit-girard** [comment]
I will review this submission, yes.

**Comment by gdetor** [comment]
@anne-urai  Sure no problem.

**Comment by gdetor** [comment]
Hi @benoit-girard  @anne-urai gentle reminder

**Comment by anne-urai** [comment]
### Summary
- Gillard, Fix and Dutech replicate the IDSM model of sensorimotor habit formation by Egbert and Barandiaran. I was not familiar with this approach to habit modelling, and found the paper a pleasure to read and the code easy to run. In general, the authors explain their replication process very well, for instance in section 2.5 where they outline their attempts (and the missing information in the original paper). I have a few suggestions for further clarification, especially for readers from more cognitive backgrounds.

### Major suggestions
- As a neuroscientist unfamiliar with this type of modelling tradition, I struggled to grasp what the role and interpretation of the sensorimotor nodes is. Can we think of them as biologically plausible units (e.g. reflecting memory states that the brain/agent may occupy), or rather occupying an abstract movement space? How does the number of nodes relate to the number of sensors/motors? I found both the original paper and the ReScience article rather brief on providing an intuitive explanation of the interpretation of these nodes. Helping the reader (perhaps coming from a more cognitive tradition like myself) grasp their significance would be a major improvement over the original paper.
- a list/table of variables and their names would increase the ease with which the reader can follow the equations. The original table 1 provides this, but could be expanded with e.g. $r$, $d$, $x$, $t$ etc. for readability.
- There are quite a few cases where the authors provide very compelling explanations for differences between the original paper and their implementation. Some have been discussed with M. Egbert, but not all (e.g. the value of $k_\omega$) - would it be worth it to provide a brief list of notes differences, run it by the original authors, and give a little summary of this correspondence? 


### Running the code
- after creating the virtualenv on Mac Os 10.14.6, installing the requirements gives an error:
```
(venv) (base) anneurai-mbp-5:rescience_egbert14 urai$ pip install -r requirements
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver==1.2.0
  Downloading kiwisolver-1.2.0-cp36-cp36m-macosx_10_9_x86_64.whl (60 kB)
     |████████████████████████████████| 60 kB 2.4 MB/s 
Collecting matplotlib==3.1.1
  Downloading matplotlib-3.1.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.4 MB)
     |████████████████████████████████| 14.4 MB 10.5 MB/s 
Collecting numpy==1.17.4
  Downloading numpy-1.17.4-cp36-cp36m-macosx_10_9_x86_64.whl (15.1 MB)
     |████████████████████████████████| 15.1 MB 12.1 MB/s 
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0
(venv) (base) anneurai-mbp-5:rescience_egbert14 urai$ 

```
After commenting out `pkg-resources==0.0.0` from `requirements`, I was able to install the required packages. I was then able to run all the experimental scripts without problem at the first try, generating the figures of the paper.
- when running `exp-001.py` and `exp-002.py` there is a long list of command line output numbers that are not immediately useful or described. Consider removing those from the standard output, or perhaps only showing them with a `--verbose` option. It may also be helpful to add a status bar to give the user a sense of the time required to run each script.
- The normalization and denormalization code (from line 84 in `exp-002.py`) has several hard-coded values that have been estimated from the original figuere 5. How was this estimation performed? Could they be replaced with variables in the code, to give the reader a better idea of the functional role of these values?


### Minor details
- the pdf still says 'received 1 november 2018', and in the footnote of page 1 links to the standard Rescience code repository instead of this project's code.
- section 2.1: "The original work does not specify of these are numerically integrated." of -> i
- as I read the original paper and the replication, I found myself imagining the movement of the robots (e.g. in figure 7) from the individual time snapshots. It may be outside the scope of this replication, but I think it would be very helpful and nice to output some gifs or videos of the robot behavior to give an even better grasp of the dynamics.
- please provide a short explanation of the difference between the original equation 12 and the new equation 18, after the statement that the former is incorrectly written.

**Comment by gdetor** [comment]
@anne-urai Thank you for the review.

**Comment by snowgoon88** [comment]
@anne-urai Thank you for this helpful and valuable comments. We will definitively use them to improve readability and ease of use.
One thing to note, though, the discussion with M. Egbert was quite short and it has been a while since he did not respond to our last questions. We send him the current version of the paper, and still no reaction.

**Comment by gdetor** [comment]
@benoit-girard Gentle reminder

**Comment by rougier** [comment]
@gdetor You can also try to contact him by mail (in case he disabled email notification)

**Comment by benoit-girard** [comment]
Sorry, I am back on track after a long period where no time was left for ReScience. I will deliver my review in the coming days.

**Comment by benoit-girard** [comment]
I am done with reading the paper, launching the simulations, etc. I should be able to deliver my review tomorrow.

**Comment by benoit-girard** [comment]
The authors did a lot of work to try to reproduce the original paper, this results in a partial replication. They manage to get feedback from one of the original authors, which helped confirming some of their intuitions, but wasn't sufficently detailed to allow for perfect replication of the last experiment.

# Software

I did not manage to install the virtual environment on MacOS, but it worked fine with xubuntu.

The code is clearly written and commented. It should be easily reusable by other people interested in IDSM.

* About exp-003.py: please rename the following behavior options: SimplePhotoaxis to SimplePhototaxis and Sine Photoaxis to SinePhototaxis
* Could the authors provide the seed of the random number generator used for fig. 10, so that we can generate exactly the same figs if we want to? Indeed, from one run to another, the results seem to be quite variable, a point the authors raised to explain the differences of their results with those of the original paper.
* Could they also indicate somewhere in the paper (for example in the legend of fig. 10) how to generate the histogram of fig. 10? (I had to explore to understand that I could do that with plot_mean_sq.py)

# Paper

I have no deep concern about the paper, only minor comments:
* The reception date has not been set properly: "Received : 17th of March" (rather than 1st Nov 2018)
* section 2.1:  "w is a scalar which indicates the influence if a node, as described later." -> "of a node"?
* section 2.2: what is S in equation (2)?
* there are some line number pbs with the listing (text refers to line that are not on listing 1, and text references to listing 2 line numbers are not correct (36-37 -> 38-39))
* end of section 2.3: euqation->equation
* legend of fig. 2: representated->represented
* section 5: "This consideration also stress the importance" -> stresses

**Comment by gdetor** [comment]
@benoit-girard Thank you for the report. 
@snowgoon88 Could you address reviewrs comments?

**Comment by snowgoon88** [comment]
Hello,

@benoit-girard and @anne-urai thank you very much for the reviews. We will try to address them the best we can.
@gdetor we will tell you when the new version is ready.

have a nice day

**Comment by snowgoon88** [comment]
Hello,

@gdetor we have addressed the comments and propositions of the reviewers (detailed answer follow). The new paper and code can be found at the same URLs

PDF URL: https://members.loria.fr/ADutech/Papier/rescience_egbert14_by_GillardFixDutech.pdf
Metadata URL:
Code URL: https://gitlab.inria.fr/openbiscuit/rescience_egbert14
(code is in directory 'python', latex for paper in 'article_rescience-template')

Have a nice Day,
Alain & Jérémy

# Answers to @anne-urai  comments

## Major suggestions

* As a neuroscientist unfamiliar with this type of modelling tradition, I struggled to grasp what the role and interpretation of the sensorimotor nodes is. Can we think of them as biologically plausible units (e.g. reflecting memory states that the brain/agent may occupy), or rather occupying an abstract movement space? How does the number of nodes relate to the number of sensors/motors? I found both the original paper and the ReScience article rather brief on providing an intuitive explanation of the interpretation of these nodes. Helping the reader (perhaps coming from a more cognitive tradition like myself) grasp their significance would be a major improvement over the original paper.

**==> we have added a section 2.1 that addresses this specific point. In short :  IDSMi s not meant to be biologically plausible. The sensorimotor space should be considered as an abstract representation which ever would be its real, say, physical implementation. You are right indeed when you state the nodes act as a memory of where the agent is. But there is more. The nodes also encode the evolution of the sensorimotor state and that's one of the information used when the ISDM drives the agent (the velocity term V(x) in eq.(12) of the rescience paper). The other information being the attraction term A(x) which gears the agent so that its sensorimotor states comes back to the memorized nodes. There is no obvious relationship between the number of sensors/motors and the number of nodes. Indeed, the total number of sensors/motors encode the dimensionality of the space in which the sensoromitor states lie (their position N_p and their velocity N_v).**

* a list/table of variables and their names would increase the ease with which the reader can follow the equations. The original table 1 provides this, but could be expanded with e.g. $r$, $d$, $x$, $t$ etc. for readability.

**==> done, in table 1**

** There are quite a few cases where the authors provide very compelling explanations for differences between the original paper and their implementation. Some have been discussed with M. Egbert, but not all (e.g. the value of $k_\omega$) - would it be worth it to provide a brief list of notes differences, run it by the original authors, and give a little summary of this correspondence?

**==> the section 'Clarification by the authors about behavior generation' has been expanded. We have send this newest version to Egbert and wait for answer. BTW, Egbert did not answered our previous mail and some questions are still unanswered.** 

## Running the code

* after creating the virtualenv on Mac Os 10.14.6, installing the requirements gives an error:

**==>We deleted the unnecessary pkg-resources==0.0.0 from the requirements. We also added two notes in the readme, 1) for using python3.8 rather than python3.6 (one of use got an upgraded distro with python3.8 and the code still works with it) 2) when running the code in the virtualenv with python3.8, he got an error with numpy which required to upgrade it.**

* when running exp-001.py and exp-002.py there is a long list of command line output numbers that are not immediately useful or described. Consider removing those from the standard output, or perhaps only showing them with a --verbose option. It may also be helpful to add a status bar to give the user a sense of the time required to run each script.

**==> done**

* The normalization and denormalization code (from line 84 in exp-002.py) has several hard-coded values that have been estimated from the original figuere 5. How was this estimation performed? Could they be replaced with variables in the code, to give the reader a better idea of the functional role of these values?

**==> we added some clarification in the text about how estimation are performed. Normaization values estimation has been done "by hand" : using a ruler to measure on the figures provided by Egbert.**

## Minor details

* the pdf still says 'received 1 november 2018', and in the footnote of page 1 links to the standard Rescience code repository instead of this project's code.

**==> fixed**

* section 2.1: "The original work does not specify of these are numerically integrated." of -> i

**==> fixed**

* as I read the original paper and the replication, I found myself imagining the movement of the robots (e.g. in figure 7) from the individual time snapshots. It may be outside the scope of this replication, but I think it would be very helpful and nice to output some gifs or videos of the robot behavior to give an even better grasp of the dynamics.

**==>We created the new script movie.py for that. Generating movies is time consuming and disabled by default.**
 You can generate movies with :

    python exp-001.py --movie : the movie is exp-001.mp4
    python exp-002.py --movie : the movie is exp-002.mp4
    python exp-003.py --movie --behavior bhv : the movie is exp-003-bhv.mp4 where bhv is one of the valid behaviors

We did not incorporate the movie generation for exp-004.py hopping it is already sufficiently informative on the first three.

Movie generation (if --movie is specified) requires ffmpeg to be installed. Some example movies are attached.

[exp-003-Photophobia](https://gitlab.inria.fr/openbiscuit/rescience_egbert14/uploads/057116fd1596ece23bfa0238590f08ab/exp-003-Photophobia.mp4)

[exp-002](https://gitlab.inria.fr/openbiscuit/rescience_egbert14/uploads/31bd7c8f54d63e86391ffc7adf5fddd6/exp-002.mp4)

[exp-001](https://gitlab.inria.fr/openbiscuit/rescience_egbert14/uploads/411671e91771ef00b362672332039c36/exp-001.mp4)

* please provide a short explanation of the difference between the original equation 12 and the new equation 18, after the statement that the former is incorrectly written.

**==> We reminded the original equation (12) inside the paper. In the paper, we say that in our equation, "the scalar product between vectors b and c is correctly written, and where c is normalized" which is indeed what the author states in his paper but not what he wrote. Indeed, what he describes in plain text is the correct way to model the response of such sensor but he incorrectly transcribed that into his math equation. We could have written [<b/|b|, c/|c|>]^+ / (1+D^2) but I'm not such sure it would be clearer.**

# Answer to @benoit-girard  comments

## Software

* I did not manage to install the virtual environment on MacOS, but it worked fine with xubuntu.

**==> we updated the requirements of the virtualenv.**

* About exp-003.py: please rename the following behavior options: SimplePhotoaxis to SimplePhototaxis and Sine Photoaxis to SinePhototaxis

**==>fixed**

* Could the authors provide the seed of the random number generator used for fig. 10, so that we can generate exactly the same figs if we want to? Indeed, from one run to another, the results seem to be quite variable, a point the authors raised to explain the differences of their results with those of the original paper.

**==> we have added the --seed option to exp003 and exp004. And paper is updated accordingly (mention of the seed)**

* Could they also indicate somewhere in the paper (for example in the legend of fig. 10) how to generate the histogram of fig. 10? (I had to explore to understand that I could do that with plot_mean_sq.py)

**==> explanation added in the paper**

## Paper

* The reception date has not been set properly: "Received : 17th of March" (rather than 1st Nov 2018)

**==> fixed**

* section 2.1: "w is a scalar which indicates the influence if a node, as described later." -> "of a node"?

**==>fixed**

* section 2.2: what is S in equation (2)?

**==>removed 'S' as it was an old notation used in our preparatory tech report.**

* there are some line number pbs with the listing (text refers to line that are not on listing 1, and text references to listing 2 line numbers are not correct (36-37 -> 38-39))

**==>fixed**

* end of section 2.3: euqation->equation
* legend of fig. 2: representated->represented
* section 5: "This consideration also stress the importance" -> stresses

**==> fixed these 3 typos**

**Comment by gdetor** [comment]
Hi @benoit-girard and @anne-urai Could you please review the revised version of the paper? Thank you

**Comment by anne-urai** [comment]
Thank you for your revisions. I find the explanation in section 2.1 and the new figure very helpful. The provided videos are also great; consider linking to them from the pdf.

It is also good to have more clarity on the exchange with M. Engbert (I would suggest to include the date of the last email exchange on page 17, to give an indication of how long you've waited for a reply). Perhaps something small, but did you get approval to reprint his email responses? Perhaps Rescience has a policy for this.

I have no further suggestions, and I recommend this work to be accepted at ReScience. Thank you for your contribution!

**Comment by rougier** [comment]
@gdetor Any update?

**Comment by gdetor** [comment]
@benoit-girard Gentle reminder

**Comment by gdetor** [comment]
Hi @benoit-girard Any update on this matter?

**Comment by rougier** [comment]
@gdetor Any update?

**Comment by gdetor** [comment]
@benoit-girard Gentle reminder

**Comment by benoit-girard** [comment]
Sorry for being so late. I am fine with the revisions, they address al the questions I raised.

**Comment by gdetor** [comment]
Hi @snowgoon88 , congratulations. Both reviewers have accepted the latest version of your manuscript.
Could you please prepare the final version of your manuscript so I can proceed to its publication?

**Comment by jeremyfix** [comment]
Hi, 

In the meantime, we got some feedback by M. Egbert which in addition to addressing  some of our questions also submitted a large archive of, among others, part of the code used for the experiments in his paper.

Therefore, although we thank the reviewers for accepting the latest version of the manuscript, we need some more times to process the materials sent by M. Egbert which might, optimistically, remove some discrepancies we had in our attempts to reproduce his experiments.

**Comment by gdetor** [comment]
@jeremyfix Sounds good

**Comment by gdetor** [comment]
@jeremyfix Happy new year. Gentle reminder

**Comment by jeremyfix** [comment]
@gdetor  Thank you for the reminder; We are almost done; We should push updates pretty soon.

**Comment by snowgoon88** [comment]
Hello everyone,

@gdetor with have just commited an updated and (hopefully final) version of
the article in the git repository.

We have higlighted in *blue* what we have added/deleted in the light of the
recent exchanges with Matthew Egbert. This are "light" modifications, that
do not truly change the nature of our replication.

Matthew Egbertgave use the whole source code for all his experiments.
Looking to his code in detail, lead to some modification/editing in our
python code and some of our results are now closer to the original. Still,
2 "problems" remain and we are not totally able to replicate the results.
But we give some explanations about what could be the cause of these
discrepancies.

Thank you for your patience,
Alain, Jérémy and Tristan

Le sam. 15 janv. 2022 à 18:03, Jeremy Fix ***@***.***> a
écrit :

**Comment by gdetor** [comment]
Thank you @snowgoon88 
@anne-urai @benoit-girard Could you please review the modifications? Thank you

**Comment by anne-urai** [comment]
Hi @snowgoon88 , could you clarify which is the updated document? In https://members.loria.fr/ADutech/Papier/rescience_egbert14_by_GillardFixDutech.pdf I don't see any blue highlights, perhaps I'm overlooking something. Thanks!

**Comment by jeremyfix** [comment]
Hi @anne-urai  , you are right we forgot to update the version of the paper on the website of  Alain ; 

The updated article is available in the repo [https://gitlab.inria.fr/openbiscuit/rescience_egbert14](https://gitlab.inria.fr/openbiscuit/rescience_egbert14) and I attached the compiled PDF to this message; You can access it by clicking the link below.


[Compiled revised paper with modifications in blue](https://github.com/ReScience/submissions/files/7995790/article.pdf)

**Comment by snowgoon88** [comment]
Yes, I'm very sorry @anne-urai . I forgot to do that and I wont be able to update my web site before the 12th of february (away from the lab). Thank you Jérémy for offering an alternative.

**Comment by rougier** [comment]
Gentle reminder.

**Comment by anne-urai** [comment]
I've briefly looked at the edits in blue, and it all looks good to me. I'm happy that M. Engbert gave you such detailed feedback, you may consider adding this in an acknowledgement in the pdf.

My only final suggestion would be to add some links to the videos in the pdf, so that they are more easily findable.

**Comment by benoit-girard** [comment]
I am also fine with the edits. I also recommend acknowledging the help of M. Engbert (in fact, such acknowledgments are written page 17, but they could be moved to a dedicated section at the end of the paper).

**Comment by gdetor** [comment]
@anne-urai @benoit-girard Thank you for your comments. 
@snowgoon88 Could you please incorporate the acknowledgements in the manuscript? Once you have the paper ready I'll start the process of publishing it.

**Comment by jeremyfix** [comment]
@anne-urai @benoit-girard  @gdetor  @rougier  thank you all for your reviews; We made the changes :

- removing the obsolete texts
- adding the video links in the figure captions for exp-001, exp-002 and exp-003
- adding a dedicated acknowledgement section to better highlight the acknowledgment for the help of M. Egbert

The gitlab and PDF paper are up to date : 

PDF URL: https://members.loria.fr/ADutech/Papier/rescience_egbert14_by_GillardFixDutech.pdf
Code URL: https://gitlab.inria.fr/openbiscuit/rescience_egbert14

**Comment by benoit-girard** [comment]
@gdetor I am fine with the latest version of the paper, and thus endorse publication.

**Comment by gdetor** [comment]
Hi @snowgoon88 Could you please provide a final version of your manuscript so I can start the process of publishing it? I would need the bibliography file (.bib) as well. Thank you.

**Comment by jeremyfix** [comment]
Hi @gdetor 

All the latex + bib + figures sources are on the gitlab https://gitlab.inria.fr/openbiscuit/rescience_egbert14/-/tree/master/article_rescience-template

Is that sufficient for you or do we have to perform specific actions on the sources ?

**Comment by gdetor** [comment]
@jeremyfix Thank you.  That's what I need to start the process. Moreover, I will need a DOI or SWH for the source code repo (I didn't find any in your metadata.yaml file). If you don't have any please have a look [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content).

**Comment by gdetor** [comment]
Hi @jeremyfix Any updates?

**Comment by jeremyfix** [comment]
Hi @gdetor  , sorry for the delay, 

I uploaded the code on zenodo , the DOI is : https://doi.org/10.5281/zenodo.6477279  and added the DOI of the code in the metadata.yaml file.

I also brought some modifications I forgot  in the metadata file : 
 
- updated the keywords
- added the github issue link 
- added the acceptance date
- added a CC BY 4.0 license file in the code directory

**Comment by gdetor** [comment]
Thank you @jeremyfix. Congratulations, your article is now published. Here is the  [Zenodo](https://doi.org/10.5281/zenodo.6478462). Here you can find the complete
[metadata.yaml](https://github.com/ReScience/articles/tree/10.5281_zenodo.6478462/10.5281_zenodo.6478462/article.yaml) to integrate with your repository. 

Hi @rougier the article does not appear in the master branch of
 [ReScience/articles](https://github.com/ReScience/articles)
Do you have any idea why? It appears normally in its own branch but not in the master.

**Comment by gdetor** [comment]
@rougier I claimed the right Volume, Issue and Number. However, the problem remains. The previous entry does not exist in the master branch of ReScience/articles repository. So I cannot update the necessary files.

**Comment by rougier** [comment]
Did you merge the branch at the end of publication?

**Comment by gdetor** [comment]
@rougier I ran the publish.py script and as far as I remember I didn't get any errors. However, it seems that you're right. For some strange reason did not merge to the master. Should I try to merge them manually?

**Comment by gdetor** [comment]
I got a new DOI, updated all the files and the published.bi (a pull request is opened) per instructions for updating a already published article. I merged manually the branch 10.5281_zenodo.6478462  to master so now it should be fine. 

@rougier Could you please confirm that everything's fine? Thank you

**Comment by rougier** [comment]
I merged your PR and rebuild the website. You can check here: https://rescience.github.io/bibliography/Gillard_2022.html

**Comment by jeremyfix** [comment]
Thank you all very much for your reviews and your editing

**Comment by rougier** [comment]
@gdetor I think you can close the issue.
